export const restArray = [
    {
        id: 0,
        title: "Пицца плюс",
        time: 50,
        rating: 4.5,
        price: 900,
        type: "Пицца",
        image: "PizzaPlus",
    },
    {
        id: 1,
        title: "Тануки",
        time: 50,
        rating: 4.5,
        price: 900,
        type: "Пицца",
        image: "Tanuki",
    },
    {
        id: 2,
        title: "FoodBand",
        time: 50,
        rating: 4.5,
        price: 900,
        type: "Пицца",
        image: "FoodBand",
    },
    {
        id: 3,
        title: "Жадина-пицца",
        time: 50,
        rating: 4.5,
        price: 900,
        type: "Пицца",
        image: "GreedyPizza",
    },
    {
        id: 4,
        title: "Точка еды",
        time: 50,
        rating: 4.5,
        price: 900,
        type: "Пицца",
        image: "FoodPoint",
    },
    {
        id: 5,
        title: "PizzaBurger",
        time: 50,
        rating: 4.5,
        price: 900,
        type: "Пицца",
        image: "PizzaBurger",
    },
];